<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AkunAdminSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Admin::create(['id' => 'adminbidops', 'nama_akun' => 'Bidang Operasi', 'id_pegawai' => '01hdg3jq3bx9p7mp1gbsf0qas5', 'id_pegawai_plt' => null, 'id_penempatan' => '0.4', 'tipe' => 'Admin Bidops', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminjasinfo', 'nama_akun' => 'Bidang Kerjasama Dan Informasi', 'id_pegawai' => '01hdg3jnn84zq1khy286apzzp2', 'id_pegawai_plt' => null, 'id_penempatan' => '0.5', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsekretariat', 'nama_akun' => 'Sekretariat', 'id_pegawai' => '01hdg3jq2bwfjchts0jshr26sw', 'id_pegawai_plt' => null, 'id_penempatan' => '0.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsuper', 'nama_akun' => 'Bidang Sarana Operasi', 'id_pegawai' => '01hdg3jpe3pt8tactwqbvecx7p', 'id_pegawai_plt' => null, 'id_penempatan' => '0.7', 'tipe' => 'Admin Dinas', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admincegah', 'nama_akun' => 'Bidang Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jn3ewz6zkby0zdfzcwtf', 'id_pegawai_plt' => null, 'id_penempatan' => '0.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsudin11', 'nama_akun' => 'Sudin Jakarta Pusat', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jnsntsktnktw4jd4r76k', 'id_penempatan' => '1.1', 'tipe' => 'Admin Sudin', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.11', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Gambir', 'id_pegawai' => '01hdg3jp95y6jhf7n6r62eagqw', 'id_pegawai_plt' => null, 'id_penempatan' => '1.11', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.12', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Sawah Besar', 'id_pegawai' => '01hdg3jp34e3tt0rxccwjj2vvw', 'id_pegawai_plt' => null, 'id_penempatan' => '1.12', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.13', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Kemayoran', 'id_pegawai' => '01hdg3jms6q3faz1pgzf6r6cxd', 'id_pegawai_plt' => null, 'id_penempatan' => '1.13', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.14', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Senen', 'id_pegawai' => '01hdg3jn0q7j8zzv6255repfdr', 'id_pegawai_plt' => null, 'id_penempatan' => '1.14', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.15', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Cempaka Putih', 'id_pegawai' => '01hdg3jp69jpa5w56sanbp1gsg', 'id_pegawai_plt' => null, 'id_penempatan' => '1.15', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.16', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Menteng', 'id_pegawai' => '01hdg3jpdjrqvzp76p8rb21pda', 'id_pegawai_plt' => null, 'id_penempatan' => '1.16', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.17', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Tanah Abang', 'id_pegawai' => '01hdg3jq50apg2mr80z8w9anb9', 'id_pegawai_plt' => null, 'id_penempatan' => '1.17', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin1.18', 'nama_akun' => 'Sudin Jakarta Pusat Sektor Johar Baru', 'id_pegawai' => '01hdg3jnsntsktnktw4jd4r76k', 'id_pegawai_plt' => null, 'id_penempatan' => '1.18', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubops11', 'nama_akun' => 'Sudin Jakarta Pusat Seksi Operasi', 'id_pegawai' => '01hdg3jmgxxpeb364y4pphzbhk', 'id_pegawai_plt' => null, 'id_penempatan' => '1.4', 'tipe' => 'Admin Subcc', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubtu11', 'nama_akun' => 'Sudin Jakarta Pusat Subbagian Tata Usaha', 'id_pegawai' => '01hdg3jmw73k24wey4ynpa4yxk', 'id_pegawai_plt' => null, 'id_penempatan' => '1.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubcegah11', 'nama_akun' => 'Sudin Jakarta Pusat Seksi Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jpn7s8hdjsgp2ydw5trp', 'id_pegawai_plt' => null, 'id_penempatan' => '1.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsudin21', 'nama_akun' => 'Sudin Jakarta Utara', 'id_pegawai' => '01hdg3jndpqjcbaeteh0d5n2wv', 'id_pegawai_plt' => null, 'id_penempatan' => '2.1', 'tipe' => 'Admin Sudin', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.11', 'nama_akun' => 'Sudin Jakarta Utara Sektor Penjaringan', 'id_pegawai' => '01hdg3jq15g2hqfq3ypkmjv0qp', 'id_pegawai_plt' => null, 'id_penempatan' => '2.11', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.12', 'nama_akun' => 'Sudin Jakarta Utara Sektor Tanjung Priok', 'id_pegawai' => '01hdg3jmgmbjd0se3hwbj94gr2', 'id_pegawai_plt' => null, 'id_penempatan' => '2.12', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.13', 'nama_akun' => 'Sudin Jakarta Utara Sektor Koja', 'id_pegawai' => '01hdg3jn69ck0f2d9emw904y93', 'id_pegawai_plt' => null, 'id_penempatan' => '2.13', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.14', 'nama_akun' => 'Sudin Jakarta Utara Sektor Cilincing', 'id_pegawai' => '01hdg3jn317me16bcqy36cxnnn', 'id_pegawai_plt' => null, 'id_penempatan' => '2.14', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.15', 'nama_akun' => 'Sudin Jakarta Utara Sektor Pademangan', 'id_pegawai' => '01hdg3jq2h2nbvby3b4rfwy50w', 'id_pegawai_plt' => null, 'id_penempatan' => '2.15', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.16', 'nama_akun' => 'Sudin Jakarta Utara Sektor Kelapa Gading', 'id_pegawai' => '01hdg3jnvdmbkm141j1k325zf3', 'id_pegawai_plt' => null, 'id_penempatan' => '2.16', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.17', 'nama_akun' => 'Sudin Jakarta Utara Sektor Kepulauan Seribu Utara', 'id_pegawai' => '01hdg3jqhw5w1zpf3x44s3vr0a', 'id_pegawai_plt' => null, 'id_penempatan' => '2.17', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin2.18', 'nama_akun' => 'Sudin Jakarta Utara Sektor Kepulauan Seribu Selatan', 'id_pegawai' => '01hdg3jn6f8bgez24wk44f9ddg', 'id_pegawai_plt' => null, 'id_penempatan' => '2.18', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubops21', 'nama_akun' => 'Sudin Jakarta Utara Seksi Operasi', 'id_pegawai' => '01hdg3jmfetawbge0ch9rgkjad', 'id_pegawai_plt' => null, 'id_penempatan' => '2.4', 'tipe' => 'Admin Subcc', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubtu21', 'nama_akun' => 'Sudin Jakarta Utara Subbagian Tata Usaha', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jq2h2nbvby3b4rfwy50w', 'id_penempatan' => '2.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubcegah21', 'nama_akun' => 'Sudin Jakarta Utara Seksi Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jnd7v9rsvvk302g3gstr', 'id_pegawai_plt' => null, 'id_penempatan' => '2.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsudin31', 'nama_akun' => 'Sudin Jakarta Barat', 'id_pegawai' => '01hdg3jpzxmsq6r2507menee7j', 'id_pegawai_plt' => null, 'id_penempatan' => '3.1', 'tipe' => 'Admin Sudin', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.11', 'nama_akun' => 'Sudin Jakarta Barat Sektor Cengkareng', 'id_pegawai' => '01hdg3jqg806ske7ax2s4jnp8y', 'id_pegawai_plt' => null, 'id_penempatan' => '3.11', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.12', 'nama_akun' => 'Sudin Jakarta Barat Sektor Grogol Petamburan', 'id_pegawai' => '01hdg3jmfdt59s9ajdyp9r192m', 'id_pegawai_plt' => null, 'id_penempatan' => '3.12', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.13', 'nama_akun' => 'Sudin Jakarta Barat Sektor Taman Sari', 'id_pegawai' => '01hdg3jpxwkj40ce6cpdf1m0bc', 'id_pegawai_plt' => null, 'id_penempatan' => '3.13', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.14', 'nama_akun' => 'Sudin Jakarta Barat Sektor Tambora', 'id_pegawai' => '01hdg3jn9y3gq6benphgwh139s', 'id_pegawai_plt' => null, 'id_penempatan' => '3.14', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.15', 'nama_akun' => 'Sudin Jakarta Barat Sektor Kebon Jeruk', 'id_pegawai' => '01hdg3jp9mychn086v3vsk9nfs', 'id_pegawai_plt' => null, 'id_penempatan' => '3.15', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.16', 'nama_akun' => 'Sudin Jakarta Barat Sektor Kalideres', 'id_pegawai' => '01hdg3jmmzp6jfd106rsp5q9r8', 'id_pegawai_plt' => null, 'id_penempatan' => '3.16', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.17', 'nama_akun' => 'Sudin Jakarta Barat Sektor Palmerah', 'id_pegawai' => '01hdg3jpdzwxa5wqrnn4n9d8c3', 'id_pegawai_plt' => null, 'id_penempatan' => '3.17', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin3.18', 'nama_akun' => 'Sudin Jakarta Barat Sektor Kembangan', 'id_pegawai' => '01hdg3jq11ggfz67cedeza48t3', 'id_pegawai_plt' => null, 'id_penempatan' => '3.18', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubops31', 'nama_akun' => 'Sudin Jakarta Barat Seksi Operasi', 'id_pegawai' => '01hdg3jq8v0eh82egjn4gp4sn3', 'id_pegawai_plt' => null, 'id_penempatan' => '3.4', 'tipe' => 'Admin Subcc', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubtu31', 'nama_akun' => 'Sudin Jakarta Barat Subbagian Tata Usaha', 'id_pegawai' => '01hdg3jpmy88hcwsrwy3d86syv', 'id_pegawai_plt' => null, 'id_penempatan' => '3.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubcegah31', 'nama_akun' => 'Sudin Jakarta Barat Seksi Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jncjs3akbax83pekcwk1', 'id_pegawai_plt' => null, 'id_penempatan' => '3.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubops41', 'nama_akun' => 'Sudin Jakarta Selatan Seksi Operasi', 'id_pegawai' => '01hdg3jqd69v1q4bbwxk9ddwc1', 'id_pegawai_plt' => null, 'id_penempatan' => '4.4', 'tipe' => 'Admin Subcc', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsudin41', 'nama_akun' => 'Sudin Jakarta Selatan', 'id_pegawai' => '01hdg3jq7f23q6vtdfyjz4t896', 'id_pegawai_plt' => null, 'id_penempatan' => '4.1', 'tipe' => 'Admin Sudin', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.11', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Tebet', 'id_pegawai' => '01hdg3jq4794c9jmf9dt72167k', 'id_pegawai_plt' => null, 'id_penempatan' => '4.11', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.12', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Setia Budi', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jq3g85ayn6c8hpvz9wb5', 'id_penempatan' => '4.12', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.13', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Mampang Prapatan', 'id_pegawai' => '01hdg3jmkqptzagsp0r0rrwmcs', 'id_pegawai_plt' => null, 'id_penempatan' => '4.13', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.14', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Pasar Minggu', 'id_pegawai' => '01hdg3jq3g85ayn6c8hpvz9wb5', 'id_pegawai_plt' => null, 'id_penempatan' => '4.14', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.15', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Kebayoran Lama', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jq4794c9jmf9dt72167k', 'id_penempatan' => '4.15', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.16', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Cilandak', 'id_pegawai' => '01hdg3jp4rnf44jt930jjwww6a', 'id_pegawai_plt' => null, 'id_penempatan' => '4.16', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.17', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Kebayoran Baru', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jpjz5xjgmtkt81vwys0b', 'id_penempatan' => '4.17', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.18', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Pancoran', 'id_pegawai' => '01hdg3jnwfwkqzr1dh1503vc2r', 'id_pegawai_plt' => null, 'id_penempatan' => '4.18', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.19', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Jagakarsa', 'id_pegawai' => '01hdg3jpjz5xjgmtkt81vwys0b', 'id_pegawai_plt' => null, 'id_penempatan' => '4.19', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin4.20', 'nama_akun' => 'Sudin Jakarta Selatan Sektor Pesanggrahan', 'id_pegawai' => '01hdg3jmnfyaqety7pr94m2xnc', 'id_pegawai_plt' => null, 'id_penempatan' => '4.20', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubtu41', 'nama_akun' => 'Sudin Jakarta Selatan Subbagian Tata Usaha', 'id_pegawai' => '01hdg3jnf0qzw9er3fnmsqxcek', 'id_pegawai_plt' => null, 'id_penempatan' => '4.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubcegah41', 'nama_akun' => 'Sudin Jakarta Selatan Seksi Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jn7cs7yb6ec5wqsht6q7', 'id_pegawai_plt' => null, 'id_penempatan' => '4.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsudin51', 'nama_akun' => 'Sudin Jakarta Timur', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jq19jyx68g9fcp89fnqa', 'id_penempatan' => '5.1', 'tipe' => 'Admin Sudin', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.11', 'nama_akun' => 'Sudin Jakarta Timur Sektor Matraman', 'id_pegawai' => '01hdg3jp5pdq8evpqjd7kk3bw9', 'id_pegawai_plt' => null, 'id_penempatan' => '5.11', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.12', 'nama_akun' => 'Sudin Jakarta Timur Sektor Pulo Gadung', 'id_pegawai' => '01hdg3jp2xrhfseg2shkdhj6j1', 'id_pegawai_plt' => null, 'id_penempatan' => '5.12', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.13', 'nama_akun' => 'Sudin Jakarta Timur Sektor Jatinegara', 'id_pegawai' => '01hdg3jq19jyx68g9fcp89fnqa', 'id_pegawai_plt' => null, 'id_penempatan' => '5.13', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.14', 'nama_akun' => 'Sudin Jakarta Timur Sektor Kramat Jati', 'id_pegawai' => '01hdg3jpdvg8vnnf0q0hs90pav', 'id_pegawai_plt' => null, 'id_penempatan' => '5.14', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.15', 'nama_akun' => 'Sudin Jakarta Timur Sektor Pasar Rebo', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jnbs6b6ffc5dafyyr1sh', 'id_penempatan' => '5.15', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.16', 'nama_akun' => 'Sudin Jakarta Timur Sektor Cakung', 'id_pegawai' => null, 'id_pegawai_plt' => '01hdg3jnkmmgst1vxba9m8pjbn', 'id_penempatan' => '5.16', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.17', 'nama_akun' => 'Sudin Jakarta Timur Sektor Duren Sawit', 'id_pegawai' => '01hdg3jpj4nm1y2a7p4pd0xq0e', 'id_pegawai_plt' => null, 'id_penempatan' => '5.17', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.18', 'nama_akun' => 'Sudin Jakarta Timur Sektor Makassar', 'id_pegawai' => '01hdg3jq0frrr6n3c0ag3hv1dx', 'id_pegawai_plt' => null, 'id_penempatan' => '5.18', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.19', 'nama_akun' => 'Sudin Jakarta Timur Sektor Ciracas', 'id_pegawai' => '01hdg3jpy4m24zf416jvqnq5pw', 'id_pegawai_plt' => null, 'id_penempatan' => '5.19', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'admin5.20', 'nama_akun' => 'Sudin Jakarta Timur Sektor Cipayung', 'id_pegawai' => '01hdg3jq6rvyt0cmb6qhdcmq38', 'id_pegawai_plt' => null, 'id_penempatan' => '5.20', 'tipe' => 'Admin Sektor', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubops51', 'nama_akun' => 'Sudin Jakarta Timur Seksi Operasi', 'id_pegawai' => '01hdg3jnkmmgst1vxba9m8pjbn', 'id_pegawai_plt' => null, 'id_penempatan' => '5.4', 'tipe' => 'Admin Subcc', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubtu51', 'nama_akun' => 'Sudin Jakarta Timur Subbagian Tata Usaha', 'id_pegawai' => '01hdg3jmq3pejn5n3vdtktbedr', 'id_pegawai_plt' => null, 'id_penempatan' => '5.6', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminsubcegah51', 'nama_akun' => 'Sudin Jakarta Timur Seksi Pencegahan Kebakaran', 'id_pegawai' => '01hdg3jnbs6b6ffc5dafyyr1sh', 'id_pegawai_plt' => null, 'id_penempatan' => '5.8', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminpusdik', 'nama_akun' => 'Pusdiklatkar', 'id_pegawai' => '01hdg3jp0rw2a24pyg7hv8rxa5', 'id_pegawai_plt' => null, 'id_penempatan' => '7.1', 'tipe' => 'Admin Pusdik', 'password' => Hash::make('123456')]);
        Admin::create(['id' => 'adminlab', 'nama_akun' => 'Laboratorium', 'id_pegawai' => '01hdg3jnr39wj2gdcrehz8mq94', 'id_pegawai_plt' => null, 'id_penempatan' => '8.1', 'tipe' => 'Admin Lab', 'password' => Hash::make('123456')]);
    }
}
